### ISSUE TITLE
Remove num_blocks keyword in background.ipynb

### ISSUE THREAD

**Issue by JeffWalton-PSC** [martibosch/detectree-examples#2]
In notebook background.ipynb, **Image descriptor** paragraph, cell 10,
```num_blocks=num_blocks,``` keyword is not needed by ```compute_image_descriptor_from_filepath()```

**Comment by martibosch** [comment]
That is indeed a mistake, thank you for pointing it out. This has been fixed in [bdba00](https://github.com/martibosch/detectree-example/commit/bdba001c0fb9876198e84139c89b8ee7d2bab72c)

**Comment by JeffWalton-PSC** [comment]
This has been fixed.
