### ISSUE TITLE
Suggest adding dependency information to README.md

### ISSUE THREAD

**Issue by JeffWalton-PSC** [martibosch/detectree-examples#3]
Suggestion: Although the dependency information is in the ```environment.yml``` file, it would be helpful to the user to include a list of dependencies in ```README.md``` or possibly the command line needed to create the virtual environment from the yml file.

**Comment by JeffWalton-PSC** [comment]
Information regarding the download and installation of the LAS-associated packages would be very helpful.  Installing LASzip will be a barrier for many users.

**Comment by martibosch** [comment]
If I am not mistaken, there are conda recipes in conda-forge for the LAS-associated packages which work for windows. In any case, have added [some instructions to reproduce the notebooks in the README](https://github.com/martibosch/detectree-example#instructions-to-reproduce) in [7533b0](https://github.com/martibosch/detectree-example/commit/7533b0db51ba6f3a4e7f1d9ac9dfdd3fb456babf)

**Comment by JeffWalton-PSC** [comment]
The instructions are useful.  Thank you.
