### ISSUE TITLE
LaspyException: No LazBackend selected, cannot decompress data

### ISSUE THREAD

**Issue by mcclochette** [martibosch/detectree-examples#7]
While running cell 6, I ran into this error. 

> ~/anaconda3/envs/detectree/lib/python3.9/site-packages/laspy/lasreader.py in __init__(self, source, closefd, laz_backend)
>    51         if self.header.are_points_compressed:
>    52             if not laz_backend:
> ---> 53                 raise errors.LaspyException(
>     54                     "No LazBackend selected, cannot decompress data"
>     55                 )
>  LaspyException: No LazBackend selected, cannot decompress data

I don't know if there is a way it could be fixed. It seems to be related to the numpy version ?

**Comment by martibosch** [comment]
Hello @mcclochette,

Thank you for reporting this. I suppose that you mean cell 6 the "baseline.ipynb" notebook. It seems laszip must be installed via pip in order for laspy to detect the laszip backend and read compressed LIDAR. I have amended [the last commit](https://github.com/martibosch/detectree-example/commit/0fbb47e6120dd1c9801094d79988687b4b731f54) to fix this so the notebooks should be now working.

Feel free to reopen if needed. Best,
Martí

**Comment by ghost** [comment]
This solution helped me as well, but install via `conda` was not possible, had to use `pip` as suggested. 
Jfyi if somebody comes across this issue after being closed.
